apiVersion: v1
kind: Service
metadata:
  name: token-starter-service
spec:
  type: LoadBalancer
  ports:
    - name: app
      port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    app: token-starter
