name: Promote develop to master

on:
  push:
    branches:
      - develop

jobs:
  develop_to_master_promotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ github.token }}
      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
          reviewers: robo-support
          token: ${{ github.token }}
          title: "Promote develop to master"
